# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/60 * * * *"

# runs the synchronisation on startup
runOnStart: true

origin:
  # url of the origin instance
  # i.e. http://adguard.io.home.arpa
  url: http://adguard.io.home.arpa
  # apiPath: define an api path if other than "/control"
  # insecureSkipVerify: true # disable tls check
  username: admin
  password: -=PASSWORD=-
# replica instance (optional, if only one)
replica:
  # url of the replica instance
  # i.e. http://adguard.europa.home.arpa
  url: http://adguard.europa.home.arpa
  username: admin
  password: -=PASSWORD=-

# Configure the sync API server, disabled if api port is 0
#api:
  # Port, default 8080
#  port: 8080
  # if username and password are defined, basic auth is applied to the sync API
#  username: username
#  password: password

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
