version: '3'

networks:
  net:  
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

volumes:
  work:
  conf:

services:
  adguard:
    container_name: adguardhome
    hostname: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - 53:53/udp
      - 18002:80/tcp
      - 48002:443
      - 3000:3000/tcp
      - 853:853
      - 784:784/udp
      - 8853:8853/udp
      - 5443:5443
    environment:
      - TZ=Europe/Moscow
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    networks:
      net:
        ipv4_address: 172.18.0.2
    restart: unless-stopped